# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MuensterCityDistrictToolsDialog
                                 A QGIS plugin
 This plugin gives you information about the selected city district of Muenster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-10
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Martin Kriger
        email                : m.kriger@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QMessageBox
from qgis.utils import iface

from .secondDialog import Ui_DistrictProfileWindow
from .thirdDialog import Ui_ExportWindow

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Muenster_City_District_Tools_dialog_base.ui'))


class MuensterCityDistrictToolsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(MuensterCityDistrictToolsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def openSecondDialog(self):

        parent = iface.mainWindow() 

        layer = iface.activeLayer()

        features = layer.selectedFeatures()

        if len(features) != 1:
            QMessageBox.warning(parent, "Only one district", "Please check if only one district is selected")
        else:
            secondDialog = QtWidgets.QDialog()
            ui = Ui_DistrictProfileWindow()
            ui.setupUi(secondDialog)
            secondDialog.exec_()

            f = features[0]

            #logic for displaying information

    def openThirdDialog(self):

        parent = iface.mainWindow() 

        layer = iface.activeLayer()

        features = layer.selectedFeatures()

        if len(features) != 1:
            QMessageBox.warning(parent, "Only one district should", "Please check if only one district is selected")
        else:
            thirdDialog = QtWidgets.QDialog()
            ui = Ui_ExportWindow()
            ui.setupUi(thirdDialog)
            thirdDialog.exec_()

            #ui.csvExportButton.clicked.connect(Ui_ExportWindow.createCSV)

            f = features[0]
    






        

        


    